Style/Encoding:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Documentation:
  Enabled: false

AllCops:
  RunRailsCops: true
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'

